name: CI-TEST-DISPATCH
on: workflow_dispatch
#   release:
#     types: [published, deleted]

jobs:
  DeployRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.event }}"
          echo "${{ github.event_name }}"
          echo "${{ github.action }}"
          echo "${{ github.event.action }}"


