name: CI-TEST-RELEASE
on: 
  release:
    types: [published, deleted]

jobs:
  DeployRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ fromJson(github.event) }}"