name: CI-RELEASE
#on: workflow_dispatch 
on: 
  release:
    types: [published, deleted]

jobs:
  DeployRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: gettingtags
        with:
          script: |
            const action = "${{ github.event.action }}"

            const { data: releases } = await github.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 2
            })

            const result = {
              ref: releases[0].tag_name,
              tag1: releases[0].tag_name,
              tag2: action === 'deleted' ? "${{ github.ref }}" : (releases[1] ? releases[1].tag_name : releases[0].tag_name)
            }

            console.log("Output:", result);            
            return result
          result-encoding: json
      - uses: actions/checkout@v2
        name: Checkout
        with: 
          ref: "${{fromJson(steps.gettingtags.outputs.result).ref}}"
      - name: Fetching tags
        run: git fetch --all --tags           
      - name: Deploy
        run: |
          TAG1="${{fromJson(steps.gettingtags.outputs.result).tag1}}"
          TAG2="${{fromJson(steps.gettingtags.outputs.result).tag2}}"
          SERVICES=`git diff --name-only $TAG1 $TAG2 | cut -f1,2 -d'/' | sort | uniq | grep "services\w*" | cut -f2 -d '/'`
          echo "Enviroment prod"
          echo "The following services will be deployed: $SERVICES"


