name: CI-TEST
on: workflow_dispatch

jobs:
  DeployRelease:
    runs-on: ubuntu-latest
#    outputs:
#      latest-tag: ${{ steps.gettingtags.outputs.result }}
#    #  previous-tag: ${{ steps.gettingtags.outputs.previous }}
    steps:
      - uses: actions/github-script@v4
        id: gettingtags
        with:
          script: |
            const response = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 2
            })
            
            const result = {
              latest: response.data[0].tag_name,
               ...(response.data[1] && { previous: response.data[1].tag_name }),
            }
            return result
          result-encoding: json
      - name: Get result
        run: echo "${{steps.gettingtags.outputs.result.latest}}"
#      - uses: actions/checkout@v2
#        name: Checkout
#        with: 
#          ref: ${{ steps.gettingtags.outputs.result }}

