name: CI-TEST
on: workflow_dispatch

jobs:
  DeployRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: gettingtags
        with:
          script: |
            const response = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 2
            })
            
            const result = {
              latest: response.data[0].tag_name,
               ...(response.data[1] && { previous: response.data[1].tag_name }),
            }
            return result
          result-encoding: json
      - name: Tag Result
        id: tags
        run: |          
          echo "${{steps.gettingtags.outputs.result}}"
          TAGS="${{steps.gettingtags.outputs.result}}"
          echo "==="
          echo $TAGS
          echo "==="
          LATEST=$TAGS | jq '.latest'c
          echo $LATEST
          echo "?"
          echo "${{fromJson(steps.gettingtags.outputs.result).latest}}"
          echo "??"
          echo "==="
          PREVIOUS=$TAGS | jq '.previous'
          echo $PREVOUS
          echo "==="
          echo '::set-output name=LATEST::$LATEST'
          echo '::set-output name=PREVIOUS::$PREVIOUS'
      - name: Print Tags
        id: printtags
        run: |
          echo "The Latest Tag is: ${{ steps.tags.outputs.LATEST }}"
          echo "The Previous Tag is: ${{ steps.tags.outputs.PREVIOUS }}"

#      - uses: actions/checkout@v2
#        name: Checkout
#        with: 
#          ref: ${{ steps.gettingtags.outputs.result }}

