name: CI-TEST
on: workflow_dispatch

jobs:
  DeployRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: gettingtags
        with:
          script: |
            const response = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 2
            })
            
            const result = {
              latest: response.data[0].tag_name,
               ...(response.data[1] && { previous: response.data[1].tag_name }),
            }

            console.log("The Latest Tag is:", result.latest)
            if(result.previous) {
              console.log("The Previous Tag is:", result.previous)
            }
            return result
          result-encoding: json
      - uses: actions/checkout@v2
        name: Checkout
        with: 
          ref: "${{fromJson(steps.gettingtags.outputs.result).latest}}"
      - name: Deploy
        run: |
          LATEST="${{fromJson(steps.gettingtags.outputs.result).latest}}"
          PREVIOUS="${{fromJson(steps.gettingtags.outputs.result).previous}}"
          # SERVICES=`git diff --name-only refs/tags/$LATEST refs/tags/$PREVIOUS | cut -f1,2 -d'/' | sort | uniq | grep "services\w*" | cut -f2 -d '/'`
          SERVICES=`git tag`
          echo "Enviroment prod"
          echo "The following services will be deployed: $SERVICES"


