name: CI
on: 
  release:
    types: [published, deleted]

jobs:
  DeployRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
      - uses: actions/github-script@v4
        id: tags
        with:
          script: |
            const response = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 2,
            })
            console.log(reponse.data)
            const [latest, previous] = response.data
            console.log('Previous Tag', previous.tag_name)
            console.log('Latest Tag', latest.tag_name) 
            return { 
              latest, 
              previous,
            }
      - uses: actions/checkout@v2
        name: Checkout
        with: 
          ref: ${{ steps.tags.outputs.latest.tag_name }}
