name: Deploy or Rollback

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  DeployRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
      - uses: actions/github-script@v4
        id: latest
        with:
          script: |
            const result = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log('Last Tag', result.data.tag_name)
      - uses: actions/github-script@v4
        id: previous
        with:
          script: /
            const result = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log('Previous Tag', result.data.tag_name)
      - uses: actions/checkout@v2
        name: 
        with: 
          ref: ${{ steps.latest.outputs.tag_name }}
