name: CI
on: workflow_dispatch  

jobs:
  DeployRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
      - uses: actions/github-script@v4
        id: tags
        with:
          script: |
            const data = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 2,
            })
            console.log('Latest Tag', latest)
            console.log('Previous Tag', previous)
            return { 
              latest, 
              previous,
            }
      - uses: actions/checkout@v2
        name: 
        with: 
          ref: ${{ steps.tags.outputs.latest }}
