name: Deploy or Rollback

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  DeployRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)
      - uses: actions/github-script@v4
        with:
          script: |
            const result = await github.repos.getLatestRelease({
              owner: context.repo.owner,,
              repo: context.repo.repo,
            })
            console.log(result)
